datatop: remove "-pedantic"
error: vendor/qcom/opensource/dataservices/datatop/src/Android.bp:5:11: module "datatop" variant "android_vendor_arm64_armv8-a_cortex-a73": cflags: Illegal flag `-pedantic`

This is deemed an illegal flag as of I3885de831e95aeeca2ca5c0f03434e26a05c6403, remove it.

Change-Id: I54efeef3d999b28533d4656ec12321e48efe99b3